---
- name: install docker

  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: add docker repository
    yum_repository:
      name: docker repo
      description: docker-ce-repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      gpgcheck: no

  - name: install docker-ce
    yum:
      name: docker-ce
      state: latest
      